- hosts: local
  #become: yes
  #become_method: sudo
  tasks:
  - name: httpd installation - yes
    yum: name=httpd state=installed
    #yum: name=httpd state=absent
                
  - name: httpd service configuration - yes
    service: name=httpd state=started enabled=yes
    #service: name=httpd state=stopped enabled=no

