- hosts: local
  #become: yes
  #become_method: sudo

  tasks:
  - user: 
     name: admin1
     shell: /bin/bash
     groups: wheel
     append: yes

  - user: 
     name: admin2
     shell: /bin/bash
     groups: wheel
     append: yes

  - user: 
     name: guest
     shell: /bin/bash
     append: yes

  - name: Make sure we have a 'wheel' group
    group:
     name=wheel
     state=present

  - name: Allow wheel group to have passwordless sudo
    lineinfile:
     dest: /etc/sudoers
     state: present
     regexp: '^%wheel'
     line: '%wheel ALL=(ALL) NOPASSWD: ALL'

  - name: provide password for admin1
    shell: echo password.  | passwd --stdin admin1

  - name: provide password for admin2
    shell: echo password   | passwd --stdin admin2

  - name: provide password for guest
    shell: echo password  | passwd --stdin guest

  - name: locking admin2 account in default
    shell: usermod -L admin2

