- hosts: local
  #become: yes
  #become_method: sudo

  tasks:

  - name: sudoers file exists or not
    shell: test -f /etc/sudoers.bckup
    ignore_errors: true
    register: file_exists
    failed_when: file_exists.rc not in [0, 1]

  - name: put file /etc/sudoers.bckup
    shell:  cat  /etc/sudoers > /etc/sudoers.bckup
    when: file_exists.rc == 1

  - name: passwd bckup file exist or not
    shell: test -f /etc/passwd.bckup
    ignore_errors: true
    register: file_exists
    failed_when: file_exists.rc not in [0, 1]

  - name: create /etc/passwd.bckup
    shell: cat /etc/passwd > /etc/passwd.bckup
    when: file_exists.rc == 1

  - user: 
     name: admin1
     shell: /bin/bash
     groups: wheel
     append: yes

  - user: 
     name: guest1
     shell: /bin/bash
     groups: wheel
     append: yes

  - user: 
     name: guest2
     shell: /bin/bash
     append: yes

  - name: Make sure we have a 'wheel' group
    group:
     name=wheel
     state=present

  - name: Allow wheel group to have passwordless sudo
    lineinfile:
     dest: /etc/sudoers
     state: present
     regexp: '^%wheel'
     line: '%wheel ALL=(ALL) NOPASSWD: ALL'

  - name: provide password for admin1
    shell: echo password.  | passwd --stdin admin1

  - name: provide password for guest1
    shell: echo password.   | passwd --stdin guest1

  - name: provide password for guest2
    shell: echo password.  | passwd --stdin guest2

  - name: locking guest1 account in default
    shell: usermod -L guest1

