- hosts: local
  become: yes
  become_method: sudo
  tasks:
  - name: ntpd is installed
    yum: name=ntp state=installed
  - name: ntpd is running and enabled
    service: name=ntpd state=started enabled=yes

